//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAMA_RESTAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class famaDBEntities : DbContext
    {
        public famaDBEntities()
            : base("name=famaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<employeesShifts> employeesShifts { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<shifts> shifts { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
